### ISSUE TITLE
build docker image on raspberry pi 4

### ISSUE THREAD

**Issue by iioter** [mu88/ShopAndEat#1]
hi,mu88:
    I met with difficulties when build .net6 image on raspberry pi4.
use your project,it can't successful too.can  you help me?
thanks.

Step 14/23 : RUN dotnet restore "ShopAndEat/ShopAndEat.csproj"
 ---> Running in 066c444a3c0d
Aborted (core dumped)
The command '/bin/sh -c dotnet restore "ShopAndEat/ShopAndEat.csproj"' returned a non-zero code: 134

**Comment by mu88** [comment]
Hi @iioter 

I can try ;) but for doing so, I need a little more information:
- Which OS version runs on your Raspi? Bullseye or Buster?
- Are you trying to _build_ or _run_ the image on the Raspi? If you are using Buster and only want to run it, you can use my already built image `mu88/shopandeat:5.0-buster-slim-arm32v7`

[Here](https://github.com/mu88/ShopAndEat/blob/main/.github/workflows/CI.yml) you can find the GitHub Action I'm using to build the image for the Raspi.

HTH
mu88

**Comment by iioter** [comment]
hi mu88
-  I think that net6 image can't work on Buster(debian 10) OS
-  I change the OS to Bullseye(debian 11) then .net6 image works well
- Do you know how to build .net6 image on Buster(debian 10)?

**Comment by iioter** [comment]
This is my Project:
[iotgateway](https://github.com/iioter/iotgateway) for internet of things

**Comment by mu88** [comment]
>     I think that net6 image can't work on Buster(debian 10) OS
That's not entirely true: if the container will be started using `--privileged` (`docker run --privileged`), .NET 6 can be used on Buster. That's how I use my .NET 6 apps at the moment as long as I cannot move to Bullseye.

>     I change the OS to Bullseye(debian 11) then .net6 image works well
That's great news, thanks! 👏🏻

>     Do you know how to build .net6 image on Buster(debian 10)?
No, I'm sorry. But maybe it is an option for you to build your image on GitHub (as I do) for Buster and only run/consume it on the Raspi.
